version: '3.8'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      loki:
        aliases:
          - redis
    logging: *default-logging

  loki-distributor:
    image: grafana/loki:2.4.2
    container_name: loki-distributor
    restart: always
    ports:
      - 3100:3100
    depends_on:
      redis:
        condition: service_started
      consul:
        condition: service_started
      cassandra:
        condition: service_healthy
    volumes:
      - ./local-config.yaml:/etc/loki/config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/config.yaml -target=distributor
    networks:
      loki:
        aliases:
          - loki-distributor
    logging: *default-logging


  loki-querier:
    image: grafana/loki:2.4.2
    container_name: loki-querier
    restart: always
    ports:
      - 3101:3100
    depends_on:
      redis:
        condition: service_started
      consul:
        condition: service_started
      cassandra:
        condition: service_healthy
    volumes:
      - ./local-config.yaml:/etc/loki/config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/config.yaml -target=querier
    networks:
      loki:
        aliases:
          - loki-querier
    logging: *default-logging

  loki-ingester:
    image: grafana/loki:2.4.2
    container_name: loki-ingester
    restart: always
    ports:
      - 3100
    depends_on:
      redis:
        condition: service_started
      consul:
        condition: service_started
      cassandra:
        condition: service_healthy
    volumes:
      - ./local-config.yaml:/etc/loki/config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/config.yaml -target=ingester
    networks:
      loki:
        aliases:
          - loki-ingester
    logging: *default-logging

  loki-table-manager:
    image: grafana/loki:2.4.2
    container_name: loki-table-manager
    restart: always
    ports:
      - 3100
    depends_on:
      redis:
        condition: service_started
      consul:
        condition: service_started
      cassandra:
        condition: service_healthy
    volumes:
      - ./local-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -target=table-manager
    networks:
      loki:
        aliases:
          - loki-table-manager
    logging: *default-logging

  cassandra:
    image: bitnami/cassandra:3.11.11
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra:/bitnami
    restart: always
    healthcheck:
      test: [ "CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "SELECT table_name FROM system_schema.tables WHERE keyspace_name='loki';" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CLUSTER_NAME: loki
      CASSANDRA_DATACENTER: dc1
    networks:
      loki:
        aliases:
          - cassandra
    logging: *default-logging

  consul:
    container_name: consul
    restart: always
    image: consul:1.9
    command: agent -log-level=info -dev -client 0.0.0.0
    volumes:
      - consul-config:/consul/config
      - consul-data:/consul/data
    ports:
      - 8500:8500
    networks:
      loki:
        aliases:
          - consul
    logging: *default-logging

  promtail:
    image:  grafana/promtail:2.4.2
    container_name: promtail
    restart: always
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      loki-ingester:
        condition: service_started
    networks:
      loki:
        aliases:
          - promtail
    logging: *default-logging

  log-generator:
    image: mingrammer/flog
    restart: always
    command:
      - --loop
      - --format=json
      - --number=10
      - --delay=100ms
    depends_on:
      promtail:
        condition: service_started
    logging: *default-logging

  grafana:
    image: grafana/grafana:8.4.5
    container_name: grafana
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    ports:
      - "3000:3000"
    networks:
      loki:
        aliases:
          - grafana
    depends_on:
      loki-ingester:
        condition: service_started
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana:/var/lib/grafana
    logging: *default-logging

volumes:
  cassandra:
  redis_data:
  grafana:
  loki:
  consul-config:
  consul-data:

networks:
  loki:
    driver: bridge
