version: '3.8'

services:
  redis:
    image: bitnami/redis:6.0
    container_name: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379
    networks:
      - lokidemo
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3101/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development

  consul:
    container_name: consul
    image: consul:1.9
    command: agent -log-level=info -dev -client 0.0.0.0
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    ports:
      - 8500:8500
    networks:
      - lokidemo
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3101/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development

  minio:
    image: minio/minio:RELEASE.2022-03-11T23-57-45Z
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /export/loki && minio server /export'
    environment:
      - MINIO_ROOT_USER=697d0993dd097f38d5b8
      - MINIO_ROOT_PASSWORD=9f88738761b57c63f6a81bdfd471
    ports:
      - 9000:9000
    networks:
      - lokidemo
    volumes:
      - minio:/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3101/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development

  loki-distributor:
    image: grafana/loki:2.4.2
    container_name: loki-distributor
    ports:
      - 3101:3100
    depends_on:
      - minio
      - redis
      - consul
    volumes:
      - ./configs/loki/consul_config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -target=distributor
    networks:
      - lokidemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  loki-querier:
    image: grafana/loki:2.4.2
    container_name: loki-querier
    ports:
      - 3100
    depends_on:
      - minio
      - redis
      - consul
    volumes:
      - ./configs/loki/consul_config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -target=querier
    networks:
      - lokidemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  loki-ingester:
    image: grafana/loki:2.4.2
    container_name: loki-ingester
    ports:
      - 3100
    depends_on:
      - minio
      - redis
      - consul
    volumes:
      - ./configs/loki/consul_config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -target=ingester
    networks:
      - lokidemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  loki-table-manager:
    image: grafana/loki:2.4.2
    container_name: loki-table-manager
    ports:
      - 3100
    depends_on:
      - minio
      - redis
      - consul
    volumes:
      - ./configs/loki/consul_config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml -target=table-manager
    networks:
      - lokidemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  nginx-app:
    image: nginx
    container_name: nginx-app
    restart: unless-stopped
    ports:
      - 8084:80
    networks:
      - lokidemo
    depends_on:
      - loki-distributor
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3101/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=development

  cat-facts-app:
    image: alpine
    container_name: cat-facts-app
    environment:
      - SLEEP_INTERVAL=30
      - ANIMAL=cat
      - FACTS_FILE=/var/log/catfacts/facts.json
      - PROJECT_SOURCE=https://github.com/alexwohlbruck/cat-facts
    volumes:
      - /tmp/logsvol:/var/log/catfacts
    entrypoint: |
      sh -c 'sh -s << EOF
      apk add --no-cache curl
      if [ -f "$$FACTS_FILE" ] ; then rm -f $$FACTS_FILE; fi
      mkdir -p /var/log/catfacts
      while true
        do
          sleep $$SLEEP_INTERVAL
          curl -s -w "\n" "https://cat-fact.herokuapp.com/facts/random?animal_type=$$ANIMAL&amount=1" >> /var/log/catfacts/facts.json
        done
      EOF'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  promtail:
    image:  grafana/promtail:2.4.2
    container_name: promtail
    volumes:
      - /tmp/logsvol:/var/log/catfacts
      - ./configs/promtail/promtail-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - cat-facts-app
      - loki-ingester
    networks:
      - lokidemo
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - lokidemo
    depends_on:
      - loki-ingester
      - minio
    volumes:
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  minio: {}
  grafana: {}

networks:
  lokidemo: {}
